import { and, desc, eq } from "drizzle-orm";
import { db } from "./client";
import {
  workers,
  riskData,
  insurancePolicies,
  claims,
  fraudAlerts,
} from "./schema";

export type PersonaType = "rain" | "pollution" | "normal";
export type RiskLevel = "LOW" | "MEDIUM" | "HIGH";

export const insertWorker = async (input: {
  name: string;
  email: string;
  city: string;
  personaType?: PersonaType;
  deliveryPartner?: "Zomato" | "Swiggy" | "Amazon" | "Blinkit";
}) => {
  const [worker] = await db
    .insert(workers)
    .values({
      name: input.name,
      email: input.email,
      city: input.city,
      personaType: input.personaType || "rain",
      deliveryPartner: input.deliveryPartner || "Zomato",
    })
    .returning();

  return worker;
};

export const saveRiskPredictionResult = async (input: {
  city: string;
  rainProbability: number;
  aqi: number;
  temperature: number;
  riskScore: number;
  riskLevel: RiskLevel;
}) => {
  const [row] = await db
    .insert(riskData)
    .values(input)
    .returning();

  return row;
};

export const createInsurancePolicy = async (input: {
  workerId: number;
  weeklyPremium: number;
  riskLevel: RiskLevel;
  coverageAmount: number;
  status: string;
}) => {
  const [policy] = await db
    .insert(insurancePolicies)
    .values(input)
    .returning();

  return policy;
};

export const autoCreateClaim = async (input: {
  workerId: number;
  triggerType: "rain" | "pollution" | "normal";
  payoutAmount: number;
  status: "Credited" | "Under Review";
  autoGenerated?: boolean;
}) => {
  const [claim] = await db
    .insert(claims)
    .values({
      workerId: input.workerId,
      triggerType: input.triggerType,
      payoutAmount: input.payoutAmount,
      status: input.status,
      autoGenerated: input.autoGenerated ?? true,
    })
    .returning();

  return claim;
};

export const createFraudAlert = async (input: {
  workerId: number;
  reason: string;
  flagLevel: "LOW" | "MEDIUM" | "HIGH";
  resolved?: boolean;
}) => {
  const [alert] = await db
    .insert(fraudAlerts)
    .values({
      workerId: input.workerId,
      reason: input.reason,
      flagLevel: input.flagLevel,
      resolved: input.resolved ?? false,
    })
    .returning();

  return alert;
};

export const fetchDashboardData = async (workerId: number) => {
  const [worker] = await db
    .select()
    .from(workers)
    .where(eq(workers.id, workerId))
    .limit(1);

  const [activePolicy] = await db
    .select()
    .from(insurancePolicies)
    .where(and(eq(insurancePolicies.workerId, workerId), eq(insurancePolicies.status, "active")))
    .orderBy(desc(insurancePolicies.createdAt))
    .limit(1);

  const recentClaims = await db
    .select()
    .from(claims)
    .where(eq(claims.workerId, workerId))
    .orderBy(desc(claims.createdAt))
    .limit(10);

  return {
    worker,
    activePolicy: activePolicy || null,
    recentClaims,
  };
};
