import {
  pgTable,
  serial,
  text,
  timestamp,
  boolean,
  integer,
  real,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core";

export const workers = pgTable(
  "workers",
  {
    id: serial("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull(),
    city: text("city").notNull(),
    personaType: text("persona_type").notNull().default("rain"),
    deliveryPartner: text("delivery_partner").notNull().default("Zomato"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    emailIdx: uniqueIndex("workers_email_uq").on(table.email),
    cityIdx: index("workers_city_idx").on(table.city),
  }),
);

export const riskData = pgTable(
  "risk_data",
  {
    id: serial("id").primaryKey(),
    city: text("city").notNull(),
    rainProbability: real("rain_probability").notNull(),
    aqi: real("aqi").notNull(),
    temperature: real("temperature").notNull(),
    riskScore: real("risk_score").notNull(),
    riskLevel: text("risk_level").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    cityCreatedIdx: index("risk_data_city_created_idx").on(table.city, table.createdAt),
  }),
);

export const insurancePolicies = pgTable(
  "insurance_policies",
  {
    id: serial("id").primaryKey(),
    workerId: integer("worker_id")
      .references(() => workers.id, { onDelete: "cascade" })
      .notNull(),
    planId: text("plan_id").notNull().default("unknown"),
    weeklyPremium: real("weekly_premium").notNull(),
    riskLevel: text("risk_level").notNull(),
    coverageAmount: real("coverage_amount").notNull(),
    status: text("status").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    workerStatusIdx: index("insurance_policies_worker_status_idx").on(table.workerId, table.status),
  }),
);

export const claims = pgTable(
  "claims",
  {
    id: serial("id").primaryKey(),
    workerId: integer("worker_id")
      .references(() => workers.id, { onDelete: "cascade" })
      .notNull(),
    triggerType: text("trigger_type").notNull(),
    payoutAmount: real("payout_amount").notNull(),
    status: text("status").notNull(),
    autoGenerated: boolean("auto_generated").notNull().default(true),
    reviewer: text("reviewer"),
    reviewReason: text("review_reason"),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    workerCreatedIdx: index("claims_worker_created_idx").on(table.workerId, table.createdAt),
  }),
);

export const fraudAlerts = pgTable(
  "fraud_alerts",
  {
    id: serial("id").primaryKey(),
    workerId: integer("worker_id")
      .references(() => workers.id, { onDelete: "cascade" })
      .notNull(),
    reason: text("reason").notNull(),
    flagLevel: text("flag_level").notNull(),
    resolved: boolean("resolved").notNull().default(false),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (table) => ({
    workerResolvedIdx: index("fraud_alerts_worker_resolved_idx").on(table.workerId, table.resolved),
  }),
);
